### ISSUE TITLE
Record data_size column may have null issue

### ISSUE THREAD

**Issue by forshareIT** [paypal/dione#50]
## Summary

`2021-11-18T13:14:15.437225965Z	DEFAULT	Exception in thread "main" java.lang.NullPointerException: Null value appeared in non-nullable field:
2021-11-18T13:14:15.437572643Z	DEFAULT	- field (class: "scala.Long", name: "_1")
2021-11-18T13:14:15.437834819Z	DEFAULT	- root class: "scala.Tuple2"
2021-11-18T13:14:15.438102858Z	DEFAULT	If the schema is inferred from a Scala tuple/case class, or a Java bean, please try to use scala.Option[_] or other nullable types (e.g. java.lang.Integer instead of int/scala.Int).
2021-11-18T13:14:15.438328843Z	DEFAULT		at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
2021-11-18T13:14:15.43853531Z	DEFAULT		at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collectFromPlan$1.apply(Dataset.scala:3391)
2021-11-18T13:14:15.438733597Z	DEFAULT		at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collectFromPlan$1.apply(Dataset.scala:3388)
2021-11-18T13:14:15.438934459Z	DEFAULT		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
2021-11-18T13:14:15.439135423Z	DEFAULT		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
2021-11-18T13:14:15.439371529Z	DEFAULT		at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
2021-11-18T13:14:15.439572596Z	DEFAULT		at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
2021-11-18T13:14:15.439773592Z	DEFAULT		at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
2021-11-18T13:14:15.439967509Z	DEFAULT		at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
2021-11-18T13:14:15.440161591Z	DEFAULT		at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3388)
2021-11-18T13:14:15.440368416Z	DEFAULT		at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
2021-11-18T13:14:15.440566985Z	DEFAULT		at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
2021-11-18T13:14:15.440760324Z	DEFAULT		at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3369)
2021-11-18T13:14:15.440963832Z	DEFAULT		at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
2021-11-18T13:14:15.441159135Z	DEFAULT		at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
2021-11-18T13:14:15.44137152Z	DEFAULT		at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
2021-11-18T13:14:15.441567659Z	DEFAULT		at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withAction(Dataset.scala:3368)
2021-11-18T13:14:15.441793499Z	DEFAULT		at org.apache.spark.sql.Dataset.head(Dataset.scala:2550)
2021-11-18T13:14:15.441991147Z	DEFAULT		at org.apache.spark.sql.Dataset.head(Dataset.scala:2557)
2021-11-18T13:14:15.442193028Z	DEFAULT		at com.paypal.dione.spark.index.IndexManagerUtils$$anon$1.<init>(IndexManagerUtils.scala:161)
2021-11-18T13:14:15.442395756Z	DEFAULT		at com.paypal.dione.spark.index.IndexManagerUtils$.inferSize(IndexManagerUtils.scala:157)
2021-11-18T13:14:15.44260486Z	DEFAULT		at com.paypal.dione.spark.index.IndexManagerUtils$.sampleFilesAndInferSize(IndexManagerUtils.scala:134)
2021-11-18T13:14:15.442803748Z	DEFAULT		at com.paypal.dione.spark.index.IndexManagerUtils$.calcBtreeProperties(IndexManagerUtils.scala:108)
2021-11-18T13:14:15.44299733Z	DEFAULT		at com.paypal.dione.spark.index.IndexManager.appendNewPartitions(IndexManager.scala:122)
2021-11-18T13:14:15.443201121Z	DEFAULT		at com.paypal.risk.gds.index.IndexBuilder$$anonfun$buildIndex$3$$anonfun$apply$2.apply(IndexBuilder.scala:94)
2021-11-18T13:14:15.443406372Z	DEFAULT		at com.paypal.risk.gds.index.IndexBuilder$$anonfun$buildIndex$3$$anonfun$apply$2.apply(IndexBuilder.scala:92)
2021-11-18T13:14:15.457653642Z	DEFAULT		at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
2021-11-18T13:14:15.458046242Z	DEFAULT		at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
2021-11-18T13:14:15.45827662Z	DEFAULT		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-11-18T13:14:15.458484141Z	DEFAULT		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-11-18T13:14:15.458685982Z	DEFAULT		at java.lang.Thread.run(Thread.java:748)
2021-11-18T13:14:15.458958521Z	DEFAULT	2021-11-18 05:14:14 ERROR FileFormatWriter - Aborting job 4815b2e2-e798-4a64-96f5-9930468a5c32.`

Links to #PR/#Issue

## Detailed Description
data_size column may have some issue when reading the first record of one data source file like below.

![image](https://user-images.githubusercontent.com/11844914/142603347-b3ab52f2-b6d1-4dc6-b5a6-e104d6f6b48e.png)

what is the problem?
data_size may have null when buiding index

how can we solve it?
Maybe can skip to get the inputSourceBytes.
https://github.com/paypal/dione/blob/main/dione-spark/src/main/scala/com/paypal/dione/spark/index/IndexManagerUtils.scala#L164

**Comment by shay1bz** [comment]
@uzadude we can close this, right?

**Comment by uzadude** [comment]
yup, i accidentally linked the PR to itself instead of this issue..
this is resolved by #51
